/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutWindow.java
 *
 * Created on Aug 16, 2010, 3:15:59 PM
 */

package edu.williams.geoshear2013;

import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;


/**
 *
 * @author cwarren
 */
public class AboutWindow extends javax.swing.JFrame {

    /** Creates new form AboutWindow */
    public AboutWindow() {
        initComponents();
        
        // all this is used to bind the escape key to hide this window
        JPanel theContentPanel = (JPanel) this.getContentPane();
        theContentPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "hideit");
        theContentPanel.getActionMap().put("hideit", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e)
            {
               setVisible(false);
            }
        });
        
        String licenseText = "See WilliamsCollegeSoftwareLicenseVersion1.txt";
        //WilliamsCollegeSoftwareLicenseVersion1.txt
        this.jTextAreaAboutLicense.setMargin(new Insets(10,10,10,10));
        //this.jTextAreaAboutLicense.setText(licenseText);
        //InputStream input = getClass().getResourceAsStream("/edu/williams/geoshear2/WilliamsCollegeSoftwareLicenseVersion1.txt");
//        InputStreamReader in = new InputStreamReader(getClass().getResourceAsStream("/edu/williams/geoshear2/WilliamsCollegeSoftwareLicenseVersion1.txt"), "UTF-8");
        BufferedInputStream bis = new BufferedInputStream(getClass().getResourceAsStream("/edu/williams/geoshear2013/WilliamsCollegeSoftwareLicenseVersion1.txt"));
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        try {
            int result = bis.read();
            while(result != -1) {
                byte b = (byte)result;
                buf.write(b);
                result = bis.read();
            }
        } catch (IOException exc) {
            System.out.println("Could not read from WilliamsCollegeSoftwareLicenseVersion1.txt: "+ exc.toString());
        }
        //InputStreamReader in = new InputStreamReader(getClass().getR ("/edu/williams/geoshear2/WilliamsCollegeSoftwareLicenseVersion1.txt"), "UTF-8");
        this.jTextAreaAboutLicense.setText(buf.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAboutTitle = new javax.swing.JLabel();
        jLabelCopyright = new javax.swing.JLabel();
        jLabelAboutTagline = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAboutDescr = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabelLicenseTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAboutLicense = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButtonAboutClose = new javax.swing.JButton();

        setResizable(false);

        jLabelAboutTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelAboutTitle.setText("GeoShear 2.0");

        jLabelCopyright.setText("Copyright 2010 by Chris Warren and Paul Karabinos, Williams College OIT and Geology Department");

        jLabelAboutTagline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAboutTagline.setText("A program to explore and analyze shear and other deformation effects");

        jLabel1.setText(" ");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(166, 70));
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextAreaAboutDescr.setEditable(false);
        jTextAreaAboutDescr.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaAboutDescr.setColumns(20);
        jTextAreaAboutDescr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextAreaAboutDescr.setLineWrap(true);
        jTextAreaAboutDescr.setRows(5);
        jTextAreaAboutDescr.setText("This application was developed jointly, with Chris providing the programming expertise, Paul providing the subject matter expertise, and both working on the mathematics, interface, testing, and other aspects of creating a computer application.\n");
        jTextAreaAboutDescr.setWrapStyleWord(true);
        jTextAreaAboutDescr.setAlignmentX(0.0F);
        jTextAreaAboutDescr.setAutoscrolls(false);
        jTextAreaAboutDescr.setBorder(null);
        jTextAreaAboutDescr.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jTextAreaAboutDescr.setMinimumSize(new java.awt.Dimension(164, 100));
        jTextAreaAboutDescr.setPreferredSize(new java.awt.Dimension(240, 100));
        jScrollPane1.setViewportView(jTextAreaAboutDescr);

        jLabel2.setText(" ");

        jLabelLicenseTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLicenseTitle.setText("License");

        jScrollPane2.setAlignmentX(0.0F);

        jTextAreaAboutLicense.setColumns(20);
        jTextAreaAboutLicense.setLineWrap(true);
        jTextAreaAboutLicense.setRows(5);
        jTextAreaAboutLicense.setText("on instantiation this is loaded from WilliamsCollegeSoftwareLicenseVersion1.txt");
        jTextAreaAboutLicense.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaAboutLicense);

        jLabel3.setText(" ");

        jButtonAboutClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAboutClose.setText("Close");
        jButtonAboutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAboutTitle)
                            .addComponent(jLabelAboutTagline)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLicenseTitle)
                            .addComponent(jLabelCopyright)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAboutClose)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAboutTitle)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelCopyright)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAboutTagline)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelLicenseTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButtonAboutClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAboutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAboutCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAboutClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAboutTagline;
    private javax.swing.JLabel jLabelAboutTitle;
    private javax.swing.JLabel jLabelCopyright;
    private javax.swing.JLabel jLabelLicenseTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAboutDescr;
    private javax.swing.JTextArea jTextAreaAboutLicense;
    // End of variables declaration//GEN-END:variables

}
