/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.williams.geoshear2013;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author cwarren
 */
public class AutoColorOptionsDialog extends javax.swing.JFrame {

    private MainWindow launchedFromWindow;

    private boolean doAction = false;
    public int autoColorFor;
    
    public static int COLOR_ON_RF = 1;
    public static int COLOR_ON_PHI = 2;
    
    /**
     * Creates new form AutoColorOptionsDialog
     */
    public AutoColorOptionsDialog(MainWindow launchedFrom) {
        this.launchedFromWindow = launchedFrom;
        
        initComponents();
        
        this.jButtonColor1.setForeground(Util.getContrastingTextColor(this.jButtonColor1.getBackground()));
        this.jButtonColor2.setForeground(Util.getContrastingTextColor(this.jButtonColor2.getBackground()));
        this.jButtonColor3.setForeground(Util.getContrastingTextColor(this.jButtonColor3.getBackground()));
        this.jButtonColor4.setForeground(Util.getContrastingTextColor(this.jButtonColor4.getBackground()));
        this.jButtonColor5.setForeground(Util.getContrastingTextColor(this.jButtonColor5.getBackground()));
        this.jButtonColor6.setForeground(Util.getContrastingTextColor(this.jButtonColor6.getBackground()));
        this.jButtonColor7.setForeground(Util.getContrastingTextColor(this.jButtonColor7.getBackground()));
        this.jButtonColor8.setForeground(Util.getContrastingTextColor(this.jButtonColor8.getBackground()));
        this.jButtonColor9.setForeground(Util.getContrastingTextColor(this.jButtonColor9.getBackground()));
        this.jButtonColor10.setForeground(Util.getContrastingTextColor(this.jButtonColor10.getBackground()));
        this.jButtonColor11.setForeground(Util.getContrastingTextColor(this.jButtonColor11.getBackground()));
        this.jButtonColor12.setForeground(Util.getContrastingTextColor(this.jButtonColor12.getBackground()));
        
        this.setColorButtonEnablesByGroupCountSlider();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColoringSetBasis = new javax.swing.ButtonGroup();
        buttonGroupColoringRange = new javax.swing.ButtonGroup();
        jRadioButtonColorByBasePebbles = new javax.swing.JRadioButton();
        jRadioButtonColorByCurrentDeformation = new javax.swing.JRadioButton();
        jRadioButtonColorRangeFull = new javax.swing.JRadioButton();
        jRadioButtonColorRangeDynamic = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSliderNumberOfColorGroups = new javax.swing.JSlider();
        jButtonColor1 = new javax.swing.JButton();
        jButtonColor2 = new javax.swing.JButton();
        jButtonColor3 = new javax.swing.JButton();
        jButtonColor4 = new javax.swing.JButton();
        jButtonColor5 = new javax.swing.JButton();
        jButtonColor6 = new javax.swing.JButton();
        jButtonColor7 = new javax.swing.JButton();
        jButtonColor8 = new javax.swing.JButton();
        jButtonColor9 = new javax.swing.JButton();
        jButtonColor10 = new javax.swing.JButton();
        jButtonColor11 = new javax.swing.JButton();
        jButtonColor12 = new javax.swing.JButton();
        jButtonCancelAutocolor = new javax.swing.JButton();
        jButtonDoAutocolor = new javax.swing.JButton();
        jRadioButtonColorRangeByCount = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(560, 400));
        setName("autocolor_options"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupColoringSetBasis.add(jRadioButtonColorByBasePebbles);
        jRadioButtonColorByBasePebbles.setSelected(true);
        jRadioButtonColorByBasePebbles.setText("Original Pebbles");
        getContentPane().add(jRadioButtonColorByBasePebbles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        buttonGroupColoringSetBasis.add(jRadioButtonColorByCurrentDeformation);
        jRadioButtonColorByCurrentDeformation.setText("Current Pebbles");
        getContentPane().add(jRadioButtonColorByCurrentDeformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        buttonGroupColoringRange.add(jRadioButtonColorRangeFull);
        jRadioButtonColorRangeFull.setSelected(true);
        jRadioButtonColorRangeFull.setText("Equal Interval over Full Range (-90 to 90; 1 to RfMax)");
        jRadioButtonColorRangeFull.setToolTipText("min and max from cartesian rf-phi chart");
        jRadioButtonColorRangeFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonColorRangeFullActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonColorRangeFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 320, -1));

        buttonGroupColoringRange.add(jRadioButtonColorRangeDynamic);
        jRadioButtonColorRangeDynamic.setText("Equal Interval over Actual Pebble Range");
        getContentPane().add(jRadioButtonColorRangeDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 330, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number of color bins");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, 520, 30));

        jSliderNumberOfColorGroups.setMajorTickSpacing(1);
        jSliderNumberOfColorGroups.setMaximum(12);
        jSliderNumberOfColorGroups.setMinimum(2);
        jSliderNumberOfColorGroups.setPaintLabels(true);
        jSliderNumberOfColorGroups.setPaintTicks(true);
        jSliderNumberOfColorGroups.setSnapToTicks(true);
        jSliderNumberOfColorGroups.setValue(7);
        jSliderNumberOfColorGroups.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNumberOfColorGroupsStateChanged(evt);
            }
        });
        getContentPane().add(jSliderNumberOfColorGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 510, -1));

        jButtonColor1.setBackground(new java.awt.Color(255, 0, 255));
        jButtonColor1.setText("1");
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, 30));

        jButtonColor2.setBackground(new java.awt.Color(0, 255, 255));
        jButtonColor2.setText("2");
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 70, 30));

        jButtonColor3.setBackground(new java.awt.Color(255, 0, 85));
        jButtonColor3.setText("3");
        jButtonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 70, 30));

        jButtonColor4.setBackground(new java.awt.Color(0, 153, 255));
        jButtonColor4.setText("4");
        jButtonColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 30));

        jButtonColor5.setBackground(new java.awt.Color(255, 51, 204));
        jButtonColor5.setText("5");
        jButtonColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 70, 30));

        jButtonColor6.setBackground(new java.awt.Color(102, 204, 0));
        jButtonColor6.setText("6");
        jButtonColor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 70, 30));

        jButtonColor7.setBackground(new java.awt.Color(0, 85, 255));
        jButtonColor7.setText("7");
        jButtonColor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 30));

        jButtonColor8.setBackground(new java.awt.Color(102, 0, 153));
        jButtonColor8.setText("8");
        jButtonColor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 30));

        jButtonColor9.setBackground(new java.awt.Color(102, 255, 153));
        jButtonColor9.setText("9");
        jButtonColor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 70, 30));

        jButtonColor10.setBackground(new java.awt.Color(255, 255, 0));
        jButtonColor10.setText("10");
        jButtonColor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 70, 30));

        jButtonColor11.setBackground(new java.awt.Color(85, 255, 0));
        jButtonColor11.setText("11");
        jButtonColor11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 70, 30));

        jButtonColor12.setBackground(new java.awt.Color(0, 255, 0));
        jButtonColor12.setText("12");
        jButtonColor12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 70, 30));

        jButtonCancelAutocolor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelAutocolor.setText("Cancel");
        jButtonCancelAutocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAutocolorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelAutocolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 110, -1));

        jButtonDoAutocolor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDoAutocolor.setText("Auto-color the pebbles");
        jButtonDoAutocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoAutocolorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDoAutocolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        buttonGroupColoringRange.add(jRadioButtonColorRangeByCount);
        jRadioButtonColorRangeByCount.setText("Equal Number of Pebbles per Bin");
        getContentPane().add(jRadioButtonColorRangeByCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 330, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bin Configuration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pebble Data Set");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelAutocolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAutocolorActionPerformed
        this.doAction = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelAutocolorActionPerformed

    private void jButtonDoAutocolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoAutocolorActionPerformed
        this.doAction = true;
        this.setVisible(false);
        if (this.autoColorFor == AutoColorOptionsDialog.COLOR_ON_RF) {
            this.launchedFromWindow.handleDoAutoColorOnRF();
        } else
        if (this.autoColorFor == AutoColorOptionsDialog.COLOR_ON_PHI) {
            this.launchedFromWindow.handleDoAutoColorOnPhi();
        }
    }//GEN-LAST:event_jButtonDoAutocolorActionPerformed

    private void jButtonColor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor8ActionPerformed
        this.handleColorChoosingForButton(jButtonColor8);
    }//GEN-LAST:event_jButtonColor8ActionPerformed

    private void jSliderNumberOfColorGroupsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNumberOfColorGroupsStateChanged
        this.setColorButtonEnablesByGroupCountSlider();
    }//GEN-LAST:event_jSliderNumberOfColorGroupsStateChanged

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        this.handleColorChoosingForButton(jButtonColor1);
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
        this.handleColorChoosingForButton(jButtonColor2);
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButtonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor3ActionPerformed
        this.handleColorChoosingForButton(jButtonColor3);
    }//GEN-LAST:event_jButtonColor3ActionPerformed

    private void jButtonColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor4ActionPerformed
        this.handleColorChoosingForButton(jButtonColor4);
    }//GEN-LAST:event_jButtonColor4ActionPerformed

    private void jButtonColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor5ActionPerformed
        this.handleColorChoosingForButton(jButtonColor5);
    }//GEN-LAST:event_jButtonColor5ActionPerformed

    private void jButtonColor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor6ActionPerformed
        this.handleColorChoosingForButton(jButtonColor6);
    }//GEN-LAST:event_jButtonColor6ActionPerformed

    private void jButtonColor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor7ActionPerformed
        this.handleColorChoosingForButton(jButtonColor7);
    }//GEN-LAST:event_jButtonColor7ActionPerformed

    private void jButtonColor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor9ActionPerformed
        this.handleColorChoosingForButton(jButtonColor9);
    }//GEN-LAST:event_jButtonColor9ActionPerformed

    private void jButtonColor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor10ActionPerformed
        this.handleColorChoosingForButton(jButtonColor10);
    }//GEN-LAST:event_jButtonColor10ActionPerformed

    private void jButtonColor11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor11ActionPerformed
        this.handleColorChoosingForButton(jButtonColor11);
    }//GEN-LAST:event_jButtonColor11ActionPerformed

    private void jButtonColor12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor12ActionPerformed
        this.handleColorChoosingForButton(jButtonColor12);
    }//GEN-LAST:event_jButtonColor12ActionPerformed

    private void jRadioButtonColorRangeFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonColorRangeFullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonColorRangeFullActionPerformed

    private void setColorButtonEnablesByGroupCountSlider() {
        int numGroups = this.getNumberOfColorGroups();
        this.jButtonColor1.setEnabled(true);
        this.jButtonColor2.setEnabled(true);
        this.jButtonColor3.setEnabled(3<=numGroups);
        this.jButtonColor4.setEnabled(4<=numGroups);
        this.jButtonColor5.setEnabled(5<=numGroups);
        this.jButtonColor6.setEnabled(6<=numGroups);
        this.jButtonColor7.setEnabled(7<=numGroups);
        this.jButtonColor8.setEnabled(8<=numGroups);
        this.jButtonColor9.setEnabled(9<=numGroups);
        this.jButtonColor10.setEnabled(10<=numGroups);
        this.jButtonColor11.setEnabled(11<=numGroups);
        this.jButtonColor12.setEnabled(12<=numGroups);
    }
    
    private void handleColorChoosingForButton(javax.swing.JButton colorButton) {
        Color newColor = JColorChooser.showDialog (this,"Color Chooser",colorButton.getBackground());
        if (newColor != null)
        {
            colorButton.setBackground (newColor);
            colorButton.setForeground(Util.getContrastingTextColor(newColor));
        }
        this.repaint();
    }
    
    public Color getColorForGroupNumber(int groupNumber) {
        if (groupNumber == 1) { return this.jButtonColor1.getBackground(); }
        if (groupNumber == 2) { return this.jButtonColor2.getBackground(); }
        if (groupNumber == 3) { return this.jButtonColor3.getBackground(); }
        if (groupNumber == 4) { return this.jButtonColor4.getBackground(); }
        if (groupNumber == 5) { return this.jButtonColor5.getBackground(); }
        if (groupNumber == 6) { return this.jButtonColor6.getBackground(); }
        if (groupNumber == 7) { return this.jButtonColor7.getBackground(); }
        if (groupNumber == 8) { return this.jButtonColor8.getBackground(); }
        if (groupNumber == 9) { return this.jButtonColor9.getBackground(); }
        if (groupNumber == 10) { return this.jButtonColor10.getBackground(); }
        if (groupNumber == 11) { return this.jButtonColor11.getBackground(); }
        if (groupNumber == 12) { return this.jButtonColor12.getBackground(); }
        return this.jButtonColor1.getBackground();
    }
    
    public boolean isUseCurrentDeformation() {
        return this.jRadioButtonColorByCurrentDeformation.isSelected();
    }

    public int getNumberOfColorGroups() {
        return this.jSliderNumberOfColorGroups.getValue();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoColorOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoColorOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoColorOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoColorOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoColorOptionsDialog(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColoringRange;
    private javax.swing.ButtonGroup buttonGroupColoringSetBasis;
    private javax.swing.JButton jButtonCancelAutocolor;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor10;
    private javax.swing.JButton jButtonColor11;
    private javax.swing.JButton jButtonColor12;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButtonColor4;
    private javax.swing.JButton jButtonColor5;
    private javax.swing.JButton jButtonColor6;
    private javax.swing.JButton jButtonColor7;
    private javax.swing.JButton jButtonColor8;
    private javax.swing.JButton jButtonColor9;
    private javax.swing.JButton jButtonDoAutocolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonColorByBasePebbles;
    private javax.swing.JRadioButton jRadioButtonColorByCurrentDeformation;
    private javax.swing.JRadioButton jRadioButtonColorRangeByCount;
    private javax.swing.JRadioButton jRadioButtonColorRangeDynamic;
    private javax.swing.JRadioButton jRadioButtonColorRangeFull;
    private javax.swing.JSlider jSliderNumberOfColorGroups;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the doAction
     */
    public boolean isDoAction() {
        return doAction;
    }

    /**
     * @param doAction the doAction to set
     */
    public void setDoAction(boolean doAction) {
        this.doAction = doAction;
    }

    boolean isRangeFull() {
        return this.jRadioButtonColorRangeFull.isSelected();
    }

    boolean isRangeDynamic() {
        return this.jRadioButtonColorRangeDynamic.isSelected();
    }

    boolean isRangeCount() {
        return this.jRadioButtonColorRangeByCount.isSelected();
    }

    /**
     * @return the autoColorFor
     */
    public int getAutoColorFor() {
        return autoColorFor;
    }

    /**
     * @param autoColorFor the autoColorFor to set
     */
    public void setAutoColorFor(int autoColorFor) {
        this.autoColorFor = autoColorFor;
    }

}
