/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.williams.geoshear2013;

import java.awt.Color;

/**
 *
 * @author cwarren
 */
public class GSDeformationSeriesBasisDisplay extends javax.swing.JPanel implements HighlightableComponent {

    /**
     * Creates new form GSDeformationSeriesStepDisplay
     */
    public GSDeformationSeriesBasisDisplay() {
        initComponents();
    }

    public void highlight() {
        this.jLabelNumberZero.setForeground(Color.BLACK);
    }
    public void unhighlight() {
        this.jLabelNumberZero.setForeground(Color.GRAY);
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRf1 = new javax.swing.JLabel();
        jTextFieldRfCumu = new javax.swing.JTextField();
        jLabelPhi1 = new javax.swing.JLabel();
        jTextFieldPhiCumu = new javax.swing.JTextField();
        jLabelMatrixBracketLeft1 = new javax.swing.JLabel();
        jTextFieldMatrixM00Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM10Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM01Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM11Cumu = new javax.swing.JTextField();
        jLabelMatrixBracketRight1 = new javax.swing.JLabel();
        jLabelNumberZero = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(120, 198));
        setMinimumSize(new java.awt.Dimension(120, 198));
        setPreferredSize(new java.awt.Dimension(120, 198));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRf1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRf1.setText("Rs:");
        add(jLabelRf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 20, 20));

        jTextFieldRfCumu.setEditable(false);
        jTextFieldRfCumu.setText("1.00");
        jTextFieldRfCumu.setBorder(null);
        jTextFieldRfCumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldRfCumu.setEnabled(false);
        add(jTextFieldRfCumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 20));

        jLabelPhi1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhi1.setText("Phi:");
        add(jLabelPhi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 30, 20));

        jTextFieldPhiCumu.setEditable(false);
        jTextFieldPhiCumu.setText("0.00");
        jTextFieldPhiCumu.setBorder(null);
        jTextFieldPhiCumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPhiCumu.setEnabled(false);
        add(jTextFieldPhiCumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 20));

        jLabelMatrixBracketLeft1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketLeft1.setText("[");
        add(jLabelMatrixBracketLeft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 70));

        jTextFieldMatrixM00Cumu.setEditable(false);
        jTextFieldMatrixM00Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM00Cumu.setText("1.000");
        jTextFieldMatrixM00Cumu.setBorder(null);
        jTextFieldMatrixM00Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM00Cumu.setEnabled(false);
        add(jTextFieldMatrixM00Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 40, 20));

        jTextFieldMatrixM10Cumu.setEditable(false);
        jTextFieldMatrixM10Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM10Cumu.setText("0.000");
        jTextFieldMatrixM10Cumu.setBorder(null);
        jTextFieldMatrixM10Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM10Cumu.setEnabled(false);
        add(jTextFieldMatrixM10Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 40, 20));

        jTextFieldMatrixM01Cumu.setEditable(false);
        jTextFieldMatrixM01Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM01Cumu.setText("0.000");
        jTextFieldMatrixM01Cumu.setBorder(null);
        jTextFieldMatrixM01Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM01Cumu.setEnabled(false);
        add(jTextFieldMatrixM01Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, 20));

        jTextFieldMatrixM11Cumu.setEditable(false);
        jTextFieldMatrixM11Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM11Cumu.setText("1.000");
        jTextFieldMatrixM11Cumu.setBorder(null);
        jTextFieldMatrixM11Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM11Cumu.setEnabled(false);
        add(jTextFieldMatrixM11Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 20));

        jLabelMatrixBracketRight1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketRight1.setText("]");
        jLabelMatrixBracketRight1.setRequestFocusEnabled(false);
        add(jLabelMatrixBracketRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 70));

        jLabelNumberZero.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelNumberZero.setForeground(Color.GRAY);
        jLabelNumberZero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumberZero.setText("#0");
        add(jLabelNumberZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 50));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMatrixBracketLeft1;
    private javax.swing.JLabel jLabelMatrixBracketRight1;
    private javax.swing.JLabel jLabelNumberZero;
    private javax.swing.JLabel jLabelPhi1;
    private javax.swing.JLabel jLabelRf1;
    private javax.swing.JTextField jTextFieldMatrixM00Cumu;
    private javax.swing.JTextField jTextFieldMatrixM01Cumu;
    private javax.swing.JTextField jTextFieldMatrixM10Cumu;
    private javax.swing.JTextField jTextFieldMatrixM11Cumu;
    private javax.swing.JTextField jTextFieldPhiCumu;
    private javax.swing.JTextField jTextFieldRfCumu;
    // End of variables declaration//GEN-END:variables
}
