/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.williams.geoshear2013;

/**
 *
 * @author cwarren
 */
public class GSDeformationSeriesStepDisplay extends javax.swing.JPanel {

    /**
     * Creates new form GSDeformationSeriesStepDisplay
     */
    public GSDeformationSeriesStepDisplay(Deformation stepDef, Deformation cumuDef) {
        initComponents();
        if (stepDef != null) {
            this.jTextFieldMatrixM00Step.setText(Util.truncForDisplay(stepDef.m00,3));
            this.jTextFieldMatrixM01Step.setText(Util.truncForDisplay(stepDef.m01*-1,3));
            this.jTextFieldMatrixM10Step.setText(Util.truncForDisplay(stepDef.m10*-1,3));
            this.jTextFieldMatrixM11Step.setText(Util.truncForDisplay(stepDef.m11,3));
            GSPebble s = new GSPebble(10,10);
            s.deform(stepDef);
            this.jTextFieldRfStep.setText(Util.truncForDisplay(s.getMajorRadius()/s.getMinorRadius(),3));
            this.jTextFieldPhiStep.setText(Util.truncForDisplay(Util.toDegrees(s.getThetaRad()),2));
        }
        if (cumuDef != null) {
            this.jTextFieldMatrixM00Cumu.setText(Util.truncForDisplay(cumuDef.m00,3));
            this.jTextFieldMatrixM01Cumu.setText(Util.truncForDisplay(cumuDef.m01*-1,3));
            this.jTextFieldMatrixM10Cumu.setText(Util.truncForDisplay(cumuDef.m10*-1,3));
            this.jTextFieldMatrixM11Cumu.setText(Util.truncForDisplay(cumuDef.m11,3));
            GSPebble s = new GSPebble(10,10);
            s.deform(cumuDef);
            this.jTextFieldRfCumu.setText(Util.truncForDisplay(s.getMajorRadius()/s.getMinorRadius(),3));
            this.jTextFieldPhiCumu.setText(Util.truncForDisplay(Util.toDegrees(s.getThetaRad()),2));
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRf = new javax.swing.JLabel();
        jTextFieldRfStep = new javax.swing.JTextField();
        jLabelPhi = new javax.swing.JLabel();
        jTextFieldPhiStep = new javax.swing.JTextField();
        jLabelMatrixBracketLeft = new javax.swing.JLabel();
        jTextFieldMatrixM00Step = new javax.swing.JTextField();
        jTextFieldMatrixM10Step = new javax.swing.JTextField();
        jTextFieldMatrixM01Step = new javax.swing.JTextField();
        jTextFieldMatrixM11Step = new javax.swing.JTextField();
        jLabelMatrixBracketRight = new javax.swing.JLabel();
        jLabelRf1 = new javax.swing.JLabel();
        jTextFieldRfCumu = new javax.swing.JTextField();
        jLabelPhi1 = new javax.swing.JLabel();
        jTextFieldPhiCumu = new javax.swing.JTextField();
        jLabelMatrixBracketLeft1 = new javax.swing.JLabel();
        jTextFieldMatrixM00Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM10Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM01Cumu = new javax.swing.JTextField();
        jTextFieldMatrixM11Cumu = new javax.swing.JTextField();
        jLabelMatrixBracketRight1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(220, 198));
        setMinimumSize(new java.awt.Dimension(220, 198));
        setPreferredSize(new java.awt.Dimension(220, 198));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRf.setText("Rf:");
        add(jLabelRf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 20, 20));

        jTextFieldRfStep.setEditable(false);
        jTextFieldRfStep.setText("1.00");
        jTextFieldRfStep.setBorder(null);
        jTextFieldRfStep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldRfStep.setEnabled(false);
        add(jTextFieldRfStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 20));

        jLabelPhi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhi.setText("phi:");
        add(jLabelPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        jTextFieldPhiStep.setEditable(false);
        jTextFieldPhiStep.setText("0.00");
        jTextFieldPhiStep.setBorder(null);
        jTextFieldPhiStep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPhiStep.setEnabled(false);
        add(jTextFieldPhiStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 20));

        jLabelMatrixBracketLeft.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketLeft.setText("[");
        add(jLabelMatrixBracketLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 70));

        jTextFieldMatrixM00Step.setEditable(false);
        jTextFieldMatrixM00Step.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM00Step.setText("1.000");
        jTextFieldMatrixM00Step.setBorder(null);
        jTextFieldMatrixM00Step.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM00Step.setEnabled(false);
        add(jTextFieldMatrixM00Step, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 40, 40, 20));

        jTextFieldMatrixM10Step.setEditable(false);
        jTextFieldMatrixM10Step.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM10Step.setText("0.000");
        jTextFieldMatrixM10Step.setBorder(null);
        jTextFieldMatrixM10Step.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM10Step.setEnabled(false);
        add(jTextFieldMatrixM10Step, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 60, 40, 20));

        jTextFieldMatrixM01Step.setEditable(false);
        jTextFieldMatrixM01Step.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM01Step.setText("0.000");
        jTextFieldMatrixM01Step.setBorder(null);
        jTextFieldMatrixM01Step.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM01Step.setEnabled(false);
        add(jTextFieldMatrixM01Step, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, 20));

        jTextFieldMatrixM11Step.setEditable(false);
        jTextFieldMatrixM11Step.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM11Step.setText("1.000");
        jTextFieldMatrixM11Step.setBorder(null);
        jTextFieldMatrixM11Step.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM11Step.setEnabled(false);
        add(jTextFieldMatrixM11Step, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 20));

        jLabelMatrixBracketRight.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketRight.setText("]");
        jLabelMatrixBracketRight.setRequestFocusEnabled(false);
        add(jLabelMatrixBracketRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 70));

        jLabelRf1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRf1.setText("Rf:");
        add(jLabelRf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 20, 20));

        jTextFieldRfCumu.setEditable(false);
        jTextFieldRfCumu.setText("1.00");
        jTextFieldRfCumu.setBorder(null);
        jTextFieldRfCumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldRfCumu.setEnabled(false);
        add(jTextFieldRfCumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 20));

        jLabelPhi1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPhi1.setText("phi:");
        add(jLabelPhi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 30, 20));

        jTextFieldPhiCumu.setEditable(false);
        jTextFieldPhiCumu.setText("0.00");
        jTextFieldPhiCumu.setBorder(null);
        jTextFieldPhiCumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPhiCumu.setEnabled(false);
        add(jTextFieldPhiCumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 20));

        jLabelMatrixBracketLeft1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketLeft1.setText("[");
        add(jLabelMatrixBracketLeft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 70));

        jTextFieldMatrixM00Cumu.setEditable(false);
        jTextFieldMatrixM00Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM00Cumu.setText("1.000");
        jTextFieldMatrixM00Cumu.setBorder(null);
        jTextFieldMatrixM00Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM00Cumu.setEnabled(false);
        add(jTextFieldMatrixM00Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 40, 20));

        jTextFieldMatrixM10Cumu.setEditable(false);
        jTextFieldMatrixM10Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM10Cumu.setText("0.000");
        jTextFieldMatrixM10Cumu.setBorder(null);
        jTextFieldMatrixM10Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM10Cumu.setEnabled(false);
        add(jTextFieldMatrixM10Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 40, 20));

        jTextFieldMatrixM01Cumu.setEditable(false);
        jTextFieldMatrixM01Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM01Cumu.setText("0.000");
        jTextFieldMatrixM01Cumu.setBorder(null);
        jTextFieldMatrixM01Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM01Cumu.setEnabled(false);
        add(jTextFieldMatrixM01Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, 20));

        jTextFieldMatrixM11Cumu.setEditable(false);
        jTextFieldMatrixM11Cumu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatrixM11Cumu.setText("1.000");
        jTextFieldMatrixM11Cumu.setBorder(null);
        jTextFieldMatrixM11Cumu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatrixM11Cumu.setEnabled(false);
        add(jTextFieldMatrixM11Cumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 20));

        jLabelMatrixBracketRight1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabelMatrixBracketRight1.setText("]");
        jLabelMatrixBracketRight1.setRequestFocusEnabled(false);
        add(jLabelMatrixBracketRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 95, 40, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("=");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, 40));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMatrixBracketLeft;
    private javax.swing.JLabel jLabelMatrixBracketLeft1;
    private javax.swing.JLabel jLabelMatrixBracketRight;
    private javax.swing.JLabel jLabelMatrixBracketRight1;
    private javax.swing.JLabel jLabelPhi;
    private javax.swing.JLabel jLabelPhi1;
    private javax.swing.JLabel jLabelRf;
    private javax.swing.JLabel jLabelRf1;
    private javax.swing.JTextField jTextFieldMatrixM00Cumu;
    private javax.swing.JTextField jTextFieldMatrixM00Step;
    private javax.swing.JTextField jTextFieldMatrixM01Cumu;
    private javax.swing.JTextField jTextFieldMatrixM01Step;
    private javax.swing.JTextField jTextFieldMatrixM10Cumu;
    private javax.swing.JTextField jTextFieldMatrixM10Step;
    private javax.swing.JTextField jTextFieldMatrixM11Cumu;
    private javax.swing.JTextField jTextFieldMatrixM11Step;
    private javax.swing.JTextField jTextFieldPhiCumu;
    private javax.swing.JTextField jTextFieldPhiStep;
    private javax.swing.JTextField jTextFieldRfCumu;
    private javax.swing.JTextField jTextFieldRfStep;
    // End of variables declaration//GEN-END:variables
}
